INSERT INTO BRAND (NAME) VALUES ('A');
INSERT INTO BRAND (NAME) VALUES ('B');
INSERT INTO BRAND (NAME) VALUES ('C');
INSERT INTO BRAND (NAME) VALUES ('D');
INSERT INTO BRAND (NAME) VALUES ('E');
INSERT INTO BRAND (NAME) VALUES ('F');
INSERT INTO BRAND (NAME) VALUES ('G');
INSERT INTO BRAND (NAME) VALUES ('H');
INSERT INTO BRAND (NAME) VALUES ('I');

INSERT INTO CATEGORY (NAME) VALUES ('T');
INSERT INTO CATEGORY (NAME) VALUES ('O');
INSERT INTO CATEGORY (NAME) VALUES ('P');
INSERT INTO CATEGORY (NAME) VALUES ('S');
INSERT INTO CATEGORY (NAME) VALUES ('B');
INSERT INTO CATEGORY (NAME) VALUES ('H');
INSERT INTO CATEGORY (NAME) VALUES ('C');
INSERT INTO CATEGORY (NAME) VALUES ('A');

INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (1, 1, 11200);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (1, 2, 5500);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (1, 3, 4200);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (1, 7, 9000);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (1, 4, 2000);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (1, 5, 1700);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (1, 6, 1800);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (1, 7, 2300);

INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (2, 1, 10500);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (2, 2, 5900);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (2, 3, 3800);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (2, 7, 9100);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (2, 4, 2100);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (2, 5, 2000);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (2, 6, 2000);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (2, 7, 2200);

INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (3, 1, 10000);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (3, 2, 6200);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (3, 3, 3300);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (3, 7, 9200);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (3, 4, 2200);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (3, 5, 1900);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (3, 6, 2200);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (3, 7, 2100);

INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (4, 1, 10100);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (4, 2, 5100);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (4, 3, 3000);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (4, 7, 9500);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (4, 4, 2500);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (4, 5, 1500);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (4, 6, 2400);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (4, 7, 2000);

INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (5, 1, 10700);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (5, 2, 5000);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (5, 3, 3800);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (5, 7, 9900);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (5, 4, 2300);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (5, 5, 1800);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (5, 6, 2100);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (5, 7, 2100);

INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (6, 1, 11200);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (6, 2, 7200);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (6, 3, 4000);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (6, 7, 9300);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (6, 4, 2100);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (6, 5, 1600);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (6, 6, 2300);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (6, 7, 1900);

INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (7, 1, 10500);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (7, 2, 5800);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (7, 3, 3900);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (7, 7, 9000);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (7, 4, 2200);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (7, 5, 1700);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (7, 6, 2100);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (7, 7, 2900);

INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (8, 1, 10800);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (8, 2, 6300);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (8, 3, 3100);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (8, 7, 9700);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (8, 4, 2100);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (8, 5, 1600);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (8, 6, 2000);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (8, 7, 2000);


INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (9, 1, 11400);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (9, 2, 6700);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (9, 3, 3200);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (9, 7, 9500);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (9, 4, 2400);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (9, 5, 1700);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (9, 6, 1700);
INSERT INTO ITEM (BRAND_ID, CATEGORY_ID, PRICE) VALUES (9, 7, 2400);

